### ISSUE TITLE
"on TYPE catch" statements overwrite stack traces

### ISSUE THREAD

**Issue by nex3** [dart-lang/async_await#79]
The following program:

```dart
bar() {
  throw "error";
}

main() async {
  try {
    await bar();
    return true;
  } on FormatException catch (error) {
    return false;
  }
}
```

when compiled and run, produces the following stack trace:

```
Unhandled exception:
Uncaught Error: error
Stack Trace:
#0      main.<anonymous closure>.catch0 (file:///home/nweiz/goog/dart/dart/test.out.dart:28:13)
#1      main.<anonymous closure> (file:///home/nweiz/goog/dart/dart/test.out.dart:44:15)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
```

Note that this stack trace doesn't include `bar()`, where the exception is actually thrown. Inspecting the generated code shows that the exception is being rethrown without preserving stack trace information.

**Comment by kmillikin** [comment]
Yeah, that's just wrong.  Thanks for catching it.  It should be fixed in https://github.com/dart-lang/async_await/pull/80.  Let me know if it's not.
